### ISSUE TITLE
[CJS] TypeError: getVideoId is not a function

### ISSUE THREAD

**Issue by jparish3** [radiovisual/get-video-id#59]
**Describe the bug**  
After upgrade to 3.2.0 

**To Reproduce**
```js
 const getVideoId = require('get-video-id')
 const id = getVideoId('https://www.google.cz/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwj30L2MvpDVAhUFZVAKHb8CBaYQuAIIIjAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DeG1uDU0rSLw&usg=AFQjCNECyDn3DQL7U6VW2CnXQQjB0gNKqA')
 console.log(id)
```

**Expected behavior**  
to function like prior versions

**Environment**  
Where are you running the module? Node.js, browser?

**Module version**  
The version of `get-video-id` where you are experiencing this problem (3.2.0)

**Comment by jparish3** [comment]
Fixed with module import: import getVideoId from 'get-video-id'

**Comment by radiovisual** [comment]
Thanks for reporting. Seems there might a problem with the new rollup bundler. I can reproduce this as well. I think we ignored the CJS format.

**Comment by radiovisual** [comment]
Another option is to pluck off the default

```js
const getVideoId = require('get-video-id').default;

const id = getVideoId('https://www.youtube.com/vi/1234').id;
// => '1234'
```

We should fix this, or consider moving away from rollup, to avoid some of the problems of trying to maintain different types of modules.
